#!/usr/bin/env python3
"""Expand public requirements register to at least 102 full records."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REQ_PATH = ROOT / "data" / "engineering" / "requirements.json"
BM_PATH = ROOT / "data" / "engineering" / "behavioral_models.json"

ARCHS = {f"ARCH-{i:03d}" for i in range(1, 13)}
TESTS = {
    "ST-001", "ST-002", "ST-003", "IT-001", "IT-002",
    "SEC-001", "UT-001", "UT-002", "BVT-001", "BVT-002",
}
RISKS = {f"RSK-{i:03d}" for i in range(1, 8)}


def gwt(g: str, w: str, t: str) -> dict:
    return {"given": g, "when": w, "then": t}


def R(
    rid, title, text, category, priority, rationale, source, parent, arch, method, status,
    acceptance, planned=None, test_ids=None, risk_ids=None, model_ids_l=None, model_ids=None,
):
    model_ids = model_ids or set()
    arch = [a for a in (arch or []) if a in ARCHS]
    test_ids = [t for t in (test_ids or []) if t in TESTS]
    risk_ids = [r for r in (risk_ids or []) if r in RISKS]
    model_ids_l = [m for m in (model_ids_l or []) if m in model_ids]
    return {
        "id": rid,
        "title": title,
        "text": text,
        "category": category,
        "priority": priority,
        "rationale": rationale,
        "source": source,
        "parent": parent,
        "allocated_subsystem": arch[0] if arch else "ARCH-001",
        "verification_method": method,
        "linked_architecture": arch,
        "linked_risks": risk_ids,
        "linked_tests": test_ids,
        "status": status,
        "version_introduced": "Public Engineering 1.2",
        "assumptions": [],
        "constraints": [],
        "acceptance": acceptance if isinstance(acceptance, list) else [acceptance],
        "verification_planned": planned or ("PROC-" + rid),
        "verification_executed": None,
        "linked_models": model_ids_l,
        "version_verified": None,
        "evidence_slot": None,
    }


def main() -> None:
    data = json.loads(REQ_PATH.read_text(encoding="utf-8"))
    model_ids = {m["id"] for m in json.loads(BM_PATH.read_text(encoding="utf-8"))["models"]}
    existing = {r["id"]: r for r in data["requirements"]}

    def add(rec):
        if rec["id"] in existing:
            return
        existing[rec["id"]] = rec

    # Install
    add(R("REQ-INST-001", "One-command Lite install entry",
          "The system shall provide a documented single-entry installer for OtaconsKeep Lite on supported Windows hosts.",
          "Installation", "P0", "Reduces abandon rate; public install story depends on one-click path.",
          "Public Otacon install page", "REQ-SYS-001", ["ARCH-011"], "Demonstration", "Implemented",
          [gwt("supported Windows host", "operator runs published Setup.bat", "installer starts without manual dependency hunting")],
          "DEMO-INST-001", risk_ids=["RSK-005"], model_ids=model_ids))
    add(R("REQ-INST-002", "WSL feature enable with reboot resume",
          "The installer shall detect required WSL/OS feature enablement and resume setup after reboot without discarding prior progress.",
          "Installation", "P0", "WSL reboot is the dominant Windows install failure mode (RSK-005).",
          "Install honesty notes / RSK-005", "REQ-INST-001", ["ARCH-011"], "Test", "Verification Pending",
          [gwt("WSL feature not enabled", "installer triggers enable + reboot", "resume continues from last completed stage")],
          "ST-003", ["ST-003"], ["RSK-005"], model_ids=model_ids))
    add(R("REQ-INST-003", "Installer stage logging",
          "The installer shall write a stage-tagged log file with timestamps for each major install phase.",
          "Installation", "P1", "Support triage and evidence packs need reproducible logs.",
          "FAQ / Discord support", "REQ-INST-001", ["ARCH-011"], "Inspection", "Implemented",
          [gwt("install runs", "operator opens install log", "stages appear with timestamps")],
          "INSP-INST-003", model_ids=model_ids))
    add(R("REQ-INST-004", "Prerequisite detection",
          "The installer shall detect missing prerequisites (disk, virtualization, admin rights where required) before long downloads begin.",
          "Installation", "P1", "Fail-fast beats multi-hour fail-late.",
          "Install UX", "REQ-INST-001", ["ARCH-011"], "Test", "Verification Pending",
          [gwt("insufficient free disk", "installer starts", "clear fail with remediation before model download")],
          model_ids=model_ids))
    add(R("REQ-INST-005", "Linux / WSL documented path",
          "The system shall document a Linux/WSL install path functionally equivalent for Core services.",
          "Installation", "P0", "Not all operators are on Windows.",
          "Otacon page", "REQ-SYS-001", ["ARCH-011"], "Demonstration", "Implemented",
          [gwt("Ubuntu WSL or Linux", "operator follows published steps", "Core service becomes reachable locally")],
          "DEMO-INST-005", model_ids=model_ids))
    add(R("REQ-INST-006", "Soft-update without data wipe",
          "A soft-update shall refresh code/helpers without wiping agent memory stores by default.",
          "Installation", "P0", "Continuity promise fails if updates erase memory.",
          "Setup soft-update docs", "REQ-FUNC-001", ["ARCH-003", "ARCH-011"], "Test", "Verification Pending",
          [gwt("agent memory exists", "soft-update completes", "memory still readable")],
          risk_ids=["RSK-002"], model_ids=model_ids))
    add(R("REQ-INST-007", "Expansion requires Core",
          "The Expansion installer shall refuse to proceed if Core/Lite is not detected at the expected path (or OTACON_INSTALL_DIR).",
          "Installation", "P0", "Prevents half-installed Expansion footguns.",
          "FAQ Expansion", None, ["ARCH-011"], "Test", "Verification Pending",
          [gwt("Core missing", "Expansion installer runs", "fails with clear Core-not-found message")],
          model_ids=model_ids))
    add(R("REQ-INST-008", "Install health check gate",
          "The installer shall run a post-install health check before declaring completion.",
          "Installation", "P1", "Completion without health check trains false confidence.",
          "ACT-001 install activity", "REQ-INST-001", ["ARCH-011"], "Test", "Verification Pending",
          [gwt("install finishes stages", "health check fails", "completion is not claimed READY")],
          model_ids=model_ids))
    add(R("REQ-INST-009", "Idempotent re-run",
          "Re-running the installer on an already-installed Core shall be safe (no duplicate agent wipe).",
          "Installation", "P1", "Operators re-run when stuck; must not punish them.",
          "FAQ Expansion rerun", "REQ-INST-001", ["ARCH-011"], "Test", "Verification Pending",
          [gwt("Core already installed", "installer re-run", "existing agents remain")],
          model_ids=model_ids))
    add(R("REQ-INST-010", "Published download integrity metadata",
          "Public download pages shall publish integrity metadata (hash and/or size) for primary Setup artifacts when practical.",
          "Installation", "P2", "Reduces tamper/confusion risk.",
          "Security hygiene", None, ["ARCH-011"], "Inspection", "Design Intent",
          [gwt("download page open", "operator inspects metadata", "hash or size is visible for primary artifact")],
          "INSP-INST-010", model_ids=model_ids))
    add(R("REQ-INST-011", "Installer disk space estimate",
          "The installer shall warn when free disk is below a documented minimum before large downloads.",
          "Installation", "P1", "Avoid fail-late downloads.",
          "Install UX", "REQ-INST-004", ["ARCH-011"], "Test", "Design Intent",
          [gwt("low disk", "install start", "warning shown")], model_ids=model_ids))
    add(R("REQ-INST-012", "Network failure retry",
          "The installer shall allow retry after transient network failures without discarding completed stages when resume points exist.",
          "Installation", "P1", "Resume resilience.",
          "RSK-005", "REQ-INST-002", ["ARCH-011"], "Test", "Design Intent",
          [gwt("network drop mid-download", "retry", "resumes")], risk_ids=["RSK-005"], model_ids=model_ids))
    add(R("REQ-INST-013", "Uninstall guidance published",
          "Public docs shall describe how to stop services and where data lives for uninstall/cleanup.",
          "Installation", "P2", "Operator ownership.",
          "Docs", None, ["ARCH-011"], "Inspection", "Design Intent",
          [gwt("docs", "uninstall", "guidance present")], "INSP-INST-013", model_ids=model_ids))

    # Codec
    add(R("REQ-CODEC-001", "Codec conversation surface",
          "The system shall provide a Codec/Command Center conversation surface for talking to a selected agent.",
          "Usability", "P0", "About thesis: contact someone, not dump a prompt.",
          "About Codec", "REQ-FUNC-001", ["ARCH-007"], "Demonstration", "Implemented",
          [gwt("Core running", "operator opens Codec UI", "can send a message to an agent")],
          "DEMO-CODEC-001", model_ids=model_ids))
    add(R("REQ-CODEC-002", "Agent switch without session loss",
          "Switching the active agent in Codec shall not destroy other agents' persisted histories.",
          "Usability", "P0", "Multi-agent Keep requires non-destructive switching.",
          "Keep Desk / Expansion", "REQ-FUNC-001", ["ARCH-002", "ARCH-007"], "Test", "Verification Pending",
          [gwt("agents A and B have history", "operator switches A→B→A", "A history intact")],
          test_ids=["ST-001"], model_ids=model_ids))
    add(R("REQ-CODEC-003", "Local URL default",
          "The default Codec/Command Center endpoint shall bind to a local loopback address for the standard Lite path.",
          "Interface", "P0", "Local-first: no surprise public bind by default.",
          "Security / Overview", "REQ-SYS-001", ["ARCH-007"], "Inspection", "Implemented",
          [gwt("fresh Lite install", "operator reads default URL", "loopback host is used")],
          "INSP-CODEC-003", risk_ids=["RSK-001"], model_ids=model_ids))
    add(R("REQ-CODEC-004", "Streaming or progressive reply",
          "Codec replies shall support progressive display when the model runtime provides streaming tokens.",
          "Usability", "P2", "TTFT perception and Deck LIVE feel.",
          "Benchmarks TTFT", "REQ-CODEC-001", ["ARCH-004", "ARCH-007"], "Test", "Design Intent",
          [gwt("streaming-capable model", "message sent", "tokens appear before full completion OR documented non-stream fallback")],
          model_ids=model_ids))
    add(R("REQ-CODEC-005", "Voice path optional",
          "Voice input/output shall be optional and not block text Codec operation when STT/TTS is unavailable.",
          "Usability", "P1", "Text-first Keep must work on CPU-only hosts.",
          "Genome / Lite", "REQ-CODEC-001", ["ARCH-004", "ARCH-007"], "Test", "Verification Pending",
          [gwt("TTS unavailable", "text message sent", "text reply still returns")], model_ids=model_ids))
    add(R("REQ-CODEC-006", "Error surfaced to operator",
          "When model routing fails, Codec shall surface a human-readable error instead of a silent hang.",
          "Usability", "P0", "Silent hangs destroy trust.",
          "Operations", "REQ-CODEC-001", ["ARCH-004", "ARCH-007"], "Test", "Verification Pending",
          [gwt("model runtime down", "message sent", "UI shows failure within timeout")],
          test_ids=["IT-001"], model_ids=model_ids))
    add(R("REQ-CODEC-007", "Continuity context injection hook",
          "When continuity modules are enabled, Codec reply assembly shall be able to include continuity-derived context.",
          "Functional", "P1", "Math → SEQ-001 pipeline requires a hook.",
          "Math pipeline / MOD-EMO", "REQ-BEH-001", ["ARCH-002", "ARCH-007"], "Test", "Verification Pending",
          [gwt("continuity enabled + state non-default", "message sent", "assembled context includes continuity fields OR documented skip")],
          "BVT-001", ["BVT-001"], model_ids_l=["MOD-EMO-001"], model_ids=model_ids))
    add(R("REQ-CODEC-008", "Hard refresh safety",
          "Browser hard-refresh shall not wipe server-side agent memory.",
          "Reliability", "P0", "Operators hard-refresh constantly.",
          "FAQ", "REQ-FUNC-001", ["ARCH-003", "ARCH-007"], "Test", "Verification Pending",
          [gwt("memory exists", "browser hard refresh", "memory still present")], model_ids=model_ids))
    add(R("REQ-CODEC-009", "Message timeout",
          "Codec shall enforce a maximum wait timeout for model responses and surface timeout errors.",
          "Usability", "P1", "Avoid infinite spinners.",
          "Ops", "REQ-CODEC-006", ["ARCH-007"], "Test", "Design Intent",
          [gwt("backend hung", "timeout elapsed", "error shown")], model_ids=model_ids))
    add(R("REQ-CODEC-010", "Empty message rejected",
          "Codec shall reject empty messages without calling the model backend.",
          "Usability", "P2", "Waste/noise prevention.",
          "UX", "REQ-CODEC-001", ["ARCH-007"], "Test", "Design Intent",
          [gwt("empty input", "send", "no backend call")], model_ids=model_ids))

    # Memory
    add(R("REQ-MEM-001", "Conversation store durability",
          "Conversation history shall persist across service restarts on local storage.",
          "Data", "P0", "Core continuity claim.",
          "REQ-FUNC-001", "REQ-FUNC-001", ["ARCH-003"], "Test", "Verification Pending",
          [gwt("conversation saved", "service restart", "history reloadable")],
          "ST-001", ["ST-001"], ["RSK-002"], model_ids=model_ids))
    add(R("REQ-MEM-002", "Long-term memory store",
          "The system shall provide a long-term memory store distinct from raw conversation transcript where implemented.",
          "Data", "P1", "CM-09 retrieval needs durable facts.",
          "Behavioral Models", "REQ-FUNC-001", ["ARCH-003"], "Test", "Verification Pending",
          [gwt("LTM entry written", "restart", "entry retrievable")], model_ids=model_ids))
    add(R("REQ-MEM-003", "Memory isolation between agents",
          "Agent A's memory artifacts shall not be readable as Agent B's without an explicit shared-memory feature.",
          "Security", "P0", "Prevents cross-agent bleed.",
          "REQ-FUNC-001", "REQ-FUNC-001", ["ARCH-002", "ARCH-003"], "Test", "Verification Pending",
          [gwt("A and B exist", "A stores secret fact", "B cannot retrieve A's fact via normal Codec")],
          "ST-001", ["ST-001"], ["RSK-002"], model_ids=model_ids))
    add(R("REQ-MEM-004", "Export path design intent",
          "The system shall define a documented export path for operator-owned memory (even if UI is incomplete).",
          "Data", "P2", "Operator ownership implies exit option.",
          "Local-first", "REQ-SYS-001", ["ARCH-003"], "Inspection", "Design Intent",
          [gwt("docs reviewed", "operator looks for export", "documented path or explicit Not yet published")],
          model_ids=model_ids))
    add(R("REQ-MEM-005", "Corruption detection note",
          "On memory store read failure, the system shall log a clear corruption/read error rather than silently inventing empty history as success.",
          "Reliability", "P1", "Honesty: empty ≠ healthy.",
          "Risk memory loss", "REQ-MEM-001", ["ARCH-003"], "Test", "Design Intent",
          [gwt("store unreadable", "agent opened", "error logged / surfaced")],
          risk_ids=["RSK-002"], model_ids=model_ids))
    add(R("REQ-MEM-006", "Backup recommendation published",
          "Public docs shall recommend backup of the memory volume/path.",
          "Operational", "P2", "Guidance before automated backup.",
          "FAQ / docs", "REQ-MEM-001", ["ARCH-003"], "Inspection", "Design Intent",
          [gwt("docs open", "search backup", "recommendation found")], model_ids=model_ids))
    add(R("REQ-MEM-007", "Memory path configurable",
          "Advanced operators shall be able to configure the memory storage path via documented settings.",
          "Data", "P2", "Homelab layouts vary.",
          "Ops", "REQ-MEM-001", ["ARCH-003"], "Inspection", "Design Intent",
          [gwt("docs/settings", "path override", "documented")], model_ids=model_ids))
    add(R("REQ-MEM-008", "Transcript pagination",
          "Long conversation transcripts shall be loadable without requiring a single unbounded UI payload.",
          "Data", "P2", "UI stability.",
          "Codec", "REQ-MEM-001", ["ARCH-003", "ARCH-007"], "Test", "Design Intent",
          [gwt("very long history", "open Codec", "UI remains responsive or paginates")], model_ids=model_ids))

    # Behavioral / continuity
    for rec in [
        R("REQ-BEH-003", "State vector bounds",
          "Emotional continuity state variables shall remain within documented numeric bounds after every update.",
          "Functional", "P0", "CM-04 clamp invariant; prevents runaway affect.",
          "Continuity Model CM-04 / MOD-EMO-001", "REQ-BEH-001", ["ARCH-002"], "Test", "Verification Pending",
          [gwt("series of events applied", "state inspected", "all dims within [0,1] or documented range")],
          "UT-001", ["UT-001", "BVT-001"], ["RSK-006"], ["MOD-EMO-001", "MOD-CM-004"], model_ids),
        R("REQ-BEH-004", "Asymmetric blend inertia",
          "Hostile accrual and repair shall use the documented asymmetric inertia blend rule when continuity is enabled.",
          "Functional", "P1", "Personality differentiation depends on inertia asymmetry.",
          "Math blend / albedo profile", "REQ-BEH-001", ["ARCH-002"], "Test", "Verification Pending",
          [gwt("high jealousy_inertia profile", "equal magnitude +Δ and −Δ", "net effect differs as documented")],
          "UT-002", ["UT-002", "BVT-002"], None, ["MOD-EMO-001"], model_ids),
        R("REQ-BEH-005", "Idle decay toward baseline",
          "Idle time shall apply documented decay toward baseline for fast affect dimensions.",
          "Functional", "P1", "Homeostasis; CM-04 λ term.",
          "Math decay", "REQ-BEH-001", ["ARCH-002"], "Test", "Verification Pending",
          [gwt("elevated irritation", "idle ≥ decay step", "irritation decreases toward baseline")],
          "BVT-001", ["BVT-001"], None, ["MOD-EMO-001"], model_ids),
        R("REQ-BEH-006", "Comparison event accumulation",
          "Repeated comparison events shall accumulate jealousy/irritation per documented sensitivity curves when enabled.",
          "Functional", "P1", "Measurable emotion claim on About.",
          "Math comparison / About metrics", "REQ-BEH-001", ["ARCH-002"], "Test", "Verification Pending",
          [gwt("same comparison repeated", "n increases", "ΔJ increases within documented cap")],
          "BVT-001", ["BVT-001"], None, ["MOD-EMO-001"], model_ids),
        R("REQ-BEH-007", "Personality parameter vector",
          "Each continuity-enabled agent shall load a personality parameter vector modulating updates.",
          "Functional", "P1", "Same event ≠ same outcome across agents.",
          "MOD-PER-001 / About personality", "REQ-BEH-001", ["ARCH-002"], "Test", "Verification Pending",
          [gwt("two profiles differ on comparison_sensitivity", "identical comparison event", "ΔJ differs")],
          "BVT-002", ["BVT-002"], None, ["MOD-PER-001"], model_ids),
        R("REQ-BEH-008", "Directed relationships",
          "Relationship edges shall be directed (A→B need not equal B→A).",
          "Functional", "P1", "About relationships thesis + Formula 5.",
          "MOD-REL / CM-05", "REQ-BEH-001", ["ARCH-002"], "Test", "Verification Pending",
          [gwt("A→B trust updated", "B→A inspected", "values independently stored")],
          "UT-002", ["UT-002"], None, ["MOD-CM-005"], model_ids),
        R("REQ-BEH-009", "Restart persistence of continuity state",
          "Continuity state shall persist across process restart when continuity is enabled.",
          "Data", "P0", "About measurable metric: restart persistence.",
          "REQ-BEH-002 sibling", "REQ-BEH-002", ["ARCH-002", "ARCH-003"], "Test", "Verification Pending",
          [gwt("non-default state saved", "restart", "state reloaded within tolerance")],
          "BVT-001", ["BVT-001"], ["RSK-006"], ["MOD-EMO-001"], model_ids),
        R("REQ-BEH-010", "No fabricated consciousness claim",
          "Public Engineering and product copy shall not claim the Continuity Model proves consciousness.",
          "Operational", "P0", "Honesty / About feeling section.",
          "About / Math honesty", None, [], "Inspection", "Implemented",
          [gwt("Math and About pages reviewed", "search consciousness claim", "only explicit non-claim language found")],
          "INSP-BEH-010", model_ids=model_ids),
        R("REQ-BEH-011", "Emotion selection from state",
          "When emotion labels are displayed, selection shall derive from the state vector via documented scoring (CM-08) or equivalent.",
          "Functional", "P2", "Labels must not be random prompt fluff when continuity is on.",
          "CM-08", "REQ-BEH-001", ["ARCH-002"], "Test", "Design Intent",
          [gwt("state dominated by high anxiety dims", "label selected", "label consistent with documented mapping")],
          model_ids_l=["MOD-CM-008"], model_ids=model_ids),
        R("REQ-BEH-012", "Event delta caps",
          "Per-cycle or per-event affect deltas shall respect documented caps when stability layer is enabled.",
          "Reliability", "P1", "CM-13 stability; one message must not nuke relationship mass.",
          "CM-13", "REQ-BEH-003", ["ARCH-002"], "Test", "Design Intent",
          [gwt("extreme event magnitude", "update applied", "Δ within ±δ")],
          model_ids_l=["MOD-CM-013"], model_ids=model_ids),
        R("REQ-BEH-013", "Identity anchor floor",
          "Adaptive output blend shall keep identity weight β_i at or above β_min when identity anchor is enabled.",
          "Functional", "P2", "CM-15 prevents identity dissolve.",
          "CM-15", "REQ-BEH-001", ["ARCH-002"], "Test", "Design Intent",
          [gwt("adaptation pressure high", "blend computed", "β_i ≥ β_min")],
          model_ids_l=["MOD-CM-015"], model_ids=model_ids),
        R("REQ-BEH-014", "MOCK traces labeled",
          "Teaching/synthetic continuity traces published on Engineering shall be labeled MOCK.",
          "Operational", "P0", "Honesty banner pattern.",
          "Engineering accuracy policy", None, [], "Inspection", "Implemented",
          [gwt("Math worked examples open", "labels inspected", "MOCK badge present")],
          "INSP-BEH-014", model_ids=model_ids),
        R("REQ-BEH-015", "Markov stage analysis optional",
          "Discrete emotional stage transitions may be analyzed as a Markov model (CM-24) without replacing continuous state as source of truth.",
          "Functional", "P2", "Analysis layer; STM-002 alignment.",
          "CM-24 / STM-002", "REQ-BEH-001", ["ARCH-002"], "Analysis", "Design Intent",
          [gwt("stage labels exist", "analyst reviews T matrix docs", "continuous E(t) still primary")],
          model_ids_l=["MOD-CM-024"], model_ids=model_ids),
        R("REQ-BEH-016", "Apology repair path",
          "Continuity-enabled agents shall support an apology/repair event class that reduces hurt/jealousy per documented rules.",
          "Functional", "P1", "About measurable repair metric.",
          "MOD-EMO events", "REQ-BEH-001", ["ARCH-002"], "Test", "Design Intent",
          [gwt("elevated hurt", "apology event", "hurt decreases")],
          test_ids=["BVT-001"], model_ids_l=["MOD-EMO-001"], model_ids=model_ids),
        R("REQ-BEH-017", "Rival heat map",
          "Continuity shall maintain rival heat scores when comparison events name rivals.",
          "Functional", "P2", "Comparison event side state.",
          "MOD-EMO comparison", "REQ-BEH-006", ["ARCH-002"], "Test", "Design Intent",
          [gwt("comparison names rival", "heat map", "rival heat increases")],
          model_ids_l=["MOD-EMO-001"], model_ids=model_ids),
        R("REQ-BEH-018", "Disengage threshold",
          "When irritation exceeds disengage_threshold, continuity shall mark a disengage stage/label per profile.",
          "Functional", "P2", "Personality disengage_threshold.",
          "MOD-PER-001", "REQ-BEH-007", ["ARCH-002"], "Test", "Design Intent",
          [gwt("irritation above threshold", "stage readout", "disengage indicated")],
          model_ids_l=["MOD-PER-001"], model_ids=model_ids),
        R("REQ-BEH-019", "Trust recovery rate",
          "Trust recovery events shall apply profile trust_recovery coefficients.",
          "Functional", "P1", "Personality trust_recovery.",
          "MOD-PER-001", "REQ-BEH-007", ["ARCH-002"], "Test", "Design Intent",
          [gwt("two profiles", "identical repair", "trust deltas differ")],
          test_ids=["BVT-002"], model_ids_l=["MOD-PER-001"], model_ids=model_ids),
        R("REQ-BEH-020", "Social influence optional",
          "CM-06 social influence shall be optional and off unless social adapters are configured.",
          "Functional", "P2", "Social adapters are optional externals.",
          "CM-06", "REQ-BEH-001", ["ARCH-002", "ARCH-009"], "Inspection", "Design Intent",
          [gwt("fresh install", "social influence", "inactive by default")],
          model_ids_l=["MOD-CM-006"], model_ids=model_ids),
    ]:
        add(rec)

    # Routing
    for rec in [
        R("REQ-ROUTE-001", "Provider-neutral capability routing",
          "Model/capability routing shall support selecting among configured local or remote backends without rewriting agent identity.",
          "Functional", "P0", "KeepRoute / provider-neutral architecture.",
          "Architecture ModelRouter", "REQ-SYS-001", ["ARCH-004"], "Test", "Verification Pending",
          [gwt("two backends configured", "route changes", "same agent identity retained")],
          test_ids=["IT-001"], model_ids=model_ids),
        R("REQ-ROUTE-002", "VRAM-tier model suggestion",
          "Default Model path shall recommend or select a model tier appropriate to detected VRAM when using Ollama.",
          "AI/Model", "P0", "Public VRAM tiers / hardware honesty.",
          "Hardware tiers", "REQ-HW-001", ["ARCH-004", "ARCH-005"], "Demonstration", "Implemented",
          [gwt("VRAM detected", "Default Model setup", "suggested tier matches published table band")],
          "DEMO-ROUTE-002", model_ids=model_ids),
        R("REQ-ROUTE-003", "Ollama loopback default",
          "The Default Model path shall target local Ollama on loopback unless operator overrides.",
          "Interface", "P0", "Local-first default.",
          "EXT-OLLAMA", "REQ-SYS-001", ["ARCH-004", "ARCH-005"], "Inspection", "Implemented",
          [gwt("fresh Default Model config", "endpoint inspected", "loopback host")],
          "INSP-ROUTE-003", model_ids=model_ids),
        R("REQ-ROUTE-004", "Graceful missing backend",
          "If the selected backend is unreachable, routing shall fail closed with an error (no silent fallback to a different provider unless configured).",
          "Reliability", "P0", "Prevents surprise data exfil / wrong brain.",
          "Security + routing", "REQ-ROUTE-001", ["ARCH-004"], "Test", "Verification Pending",
          [gwt("backend down; no fallback configured", "request sent", "error; no alternate provider called")],
          test_ids=["IT-001"], risk_ids=["RSK-001"], model_ids=model_ids),
        R("REQ-ROUTE-005", "KeepRoute mission state",
          "KeepRoute shall preserve mission/checkpoint state across model switches for supported workflows.",
          "Functional", "P1", "KeepRoute product claim.",
          "KeepRoute 1.0", None, ["ARCH-004"], "Test", "Verification Pending",
          [gwt("mission in progress", "model switched via KeepRoute", "checkpoint retained")],
          model_ids=model_ids),
        R("REQ-ROUTE-006", "No silent model upgrade",
          "Automatic model pulls shall not replace an operator-pinned model without notice when pinning is supported.",
          "Operational", "P2", "Reproducibility for BVTs/benchmarks.",
          "Benchmarks honesty", "REQ-ROUTE-002", ["ARCH-005"], "Test", "Design Intent",
          [gwt("model pinned", "update check", "pin retained or explicit prompt")], model_ids=model_ids),
        R("REQ-ROUTE-007", "Tokens/s not claimed without label",
          "Public Engineering benchmarks shall label MEASURED vs SIMULATED vs MOCK for throughput rows.",
          "Operational", "P0", "GPU honesty requirement.",
          "Benchmarks disclaimer", None, [], "Inspection", "Implemented",
          [gwt("Benchmarks table open", "rows inspected", "each row has MEASURED/SIMULATED/MOCK")],
          "INSP-ROUTE-007", model_ids=model_ids),
        R("REQ-ROUTE-008", "STT backend selectable",
          "When STT is enabled, backend selection shall be configurable independently of LLM backend.",
          "AI/Model", "P2", "Capability routing granularity.",
          "ModelRouter", "REQ-ROUTE-001", ["ARCH-004"], "Test", "Design Intent",
          [gwt("STT enabled", "config", "STT backend field exists")], model_ids=model_ids),
        R("REQ-ROUTE-009", "TTS backend selectable",
          "When TTS is enabled, backend selection shall be configurable independently of LLM backend.",
          "AI/Model", "P2", "Capability routing granularity.",
          "ModelRouter", "REQ-ROUTE-001", ["ARCH-004"], "Test", "Design Intent",
          [gwt("TTS enabled", "config", "TTS backend field exists")], model_ids=model_ids),
        R("REQ-ROUTE-010", "Capability matrix published",
          "Engineering Overview shall publish a Lite/Expansion/Reference capability matrix.",
          "Operational", "P1", "Status board honesty.",
          "Overview", None, [], "Inspection", "Implemented",
          [gwt("Overview", "matrix", "present")], "INSP-ROUTE-010", model_ids=model_ids),
    ]:
        add(rec)

    # Security / Expansion / Perf / IF / Rel / Eng / Ops / AI / HW / Func / Data / SW / Net / Usab
    extras = [
        ("REQ-SEC-002", "No secrets in public Engineering JSON",
         "Published Engineering data files shall not contain private IPs, API keys, tokens, or private key material.",
         "Security", "P0", "Portal constraint + validator.", "Engineering constraints", None, [], "Test", "Implemented",
         [gwt("validate-engineering.py runs", "on data/", "secrets clean")], "PROC-SEC-002", ["SEC-001"], None),
        ("REQ-SEC-003", "Operator-owned credentials",
         "Integrations requiring third-party credentials shall use operator-supplied secrets, not OtaconsKeep-hosted shared accounts.",
         "Security", "P0", "Local-first + liability.", "Overview externals", "REQ-SYS-001", ["ARCH-001"], "Inspection", "Implemented",
         [gwt("Discord/HA setup docs", "reviewed", "operator credentials required")], "INSP-SEC-003", None, None),
        ("REQ-SEC-004", "License seat anti-sharing policy published",
         "Premium seat sharing policy shall be published for Expansion license unlocks.",
         "Security", "P1", "FAQ premium enforcement.", "FAQ Premium", None, [], "Inspection", "Implemented",
         [gwt("FAQ open", "sharing policy", "visible")], "INSP-SEC-004", None, None),
        ("REQ-SEC-005", "Default deny remote bind",
         "Services shall not advertise a public bind address by default in Lite docs/config.",
         "Security", "P0", "RSK-001 exposure.", "RSK-001", "REQ-CODEC-003", ["ARCH-007"], "Inspection", "Verification Pending",
         [gwt("default config", "listen address", "loopback or documented explicit override")], "INSP-SEC-005", ["SEC-001"], ["RSK-001"]),
        ("REQ-SEC-006", "Redacted evidence only",
         "Public EVID packs shall be redacted of secrets and private host identifiers.",
         "Security", "P0", "Evidence gallery honesty.", "Evidence policy", None, [], "Inspection", "Design Intent",
         [gwt("EVID object published", "reviewed", "no secrets")], "INSP-SEC-006", None, None),
        ("REQ-SEC-007", "Dependency pin guidance",
         "Release notes shall call out critical dependency upgrades that affect install security.",
         "Security", "P2", "Supply chain awareness.", "Releases", None, [], "Inspection", "Design Intent",
         [gwt("release notes", "deps", "called out or Not yet published")], None, None, None),
        ("REQ-SEC-008", "CORS default local",
         "Default web UI CORS/origin policy shall prefer local operator use.",
         "Security", "P1", "Local-first web UI.", "Web UI", "REQ-CODEC-003", ["ARCH-007"], "Inspection", "Design Intent",
         [gwt("default config", "CORS", "local-preferring")], None, None, None),
        ("REQ-EXP-001", "Expansion boundary honesty",
         "Public materials shall not claim Reference Keep multi-node farm as automatic Expansion READY on every PC.",
         "Operational", "P0", "Overview out-of-scope.", "Overview boundaries", None, [], "Inspection", "Implemented",
         [gwt("Expansion page + Overview", "reviewed", "boundary language present")], "INSP-EXP-001", None, None),
        ("REQ-EXP-002", "Aria + Deck/Codec installable",
         "Expansion foundation shall make Aria chat and Deck/Codec surfaces installable when Core is present.",
         "Functional", "P0", "Expansion claim today.", "Expansion status", None, ["ARCH-007", "ARCH-002"], "Demonstration", "Implemented",
         [gwt("Core + Expansion installed", "Deck/Codec opened", "Aria reachable")], "DEMO-EXP-002", None, None),
        ("REQ-EXP-003", "Studio optional sidecar",
         "Genome/Video Studio paths shall be marked optional and may require Docker/GPU sidecars.",
         "Operational", "P1", "Avoid false READY.", "Expansion docs", "REQ-EXP-001", ["ARCH-010"], "Inspection", "Implemented",
         [gwt("Studio docs", "reviewed", "optional/sidecar language")], "INSP-EXP-003", None, None),
        ("REQ-EXP-004", "Foundation READY meanings published",
         "FOUNDATION READY / DEGRADED / FAILED meanings shall be published for Expansion installer exits.",
         "Usability", "P1", "FAQ Expansion triage.", "FAQ", "REQ-INST-007", ["ARCH-011"], "Inspection", "Implemented",
         [gwt("FAQ", "READY meanings", "documented")], "INSP-EXP-004", None, None),
        ("REQ-EXP-005", "Licensed gate for Expansion features",
         "Expansion-gated features shall require a valid license seat where the product marks them Premium.",
         "Security", "P0", "Business + fairness.", "Premium / Expansion", None, ["ARCH-001"], "Test", "Verification Pending",
         [gwt("no license", "gated feature invoked", "access denied or unlock path shown")], None, None, None),
        ("REQ-EXP-006", "Roster schema validation",
         "Expansion foundation shall validate agent roster schema before READY.",
         "Functional", "P1", "FAQ foundation installer.", "Expansion installer", "REQ-EXP-002", ["ARCH-002"], "Test", "Verification Pending",
         [gwt("invalid roster", "foundation run", "not READY")], None, None, None),
        ("REQ-EXP-007", "Creation timestamp preserved",
         "Expansion reruns shall preserve each agent's original creation timestamp.",
         "Data", "P1", "FAQ Expansion rerun.", "FAQ", "REQ-INST-009", ["ARCH-002"], "Test", "Verification Pending",
         [gwt("rerun Expansion", "timestamps", "preserved")], None, None, None),
        ("REQ-PERF-002", "Cold start measurable",
         "Cold start duration shall be measurable and eligible for BENCH publication when MEASURED.",
         "Performance", "P2", "Benchmark plan class.", "BENCH-PLAN-001", None, ["ARCH-001"], "Test", "Design Intent",
         [gwt("service stopped", "start issued", "duration recorded")], None, None, None),
        ("REQ-PERF-003", "TTFT measurable",
         "Time-to-first-token shall be measurable for streaming-capable local chat paths.",
         "Performance", "P2", "Benchmark plan.", "BENCH-PLAN-001", "REQ-CODEC-004", ["ARCH-004"], "Test", "Design Intent",
         [gwt("streaming model", "prompt sent", "TTFT recorded")], None, None, None),
        ("REQ-PERF-004", "CPU fallback path",
         "Lite shall remain usable on sub-6GB VRAM / CPU-small-model path with reduced capability, not hard-fail.",
         "Hardware", "P0", "Overview assumption.", "Overview assumptions", "REQ-HW-001", ["ARCH-005"], "Demonstration", "Verification Pending",
         [gwt("low VRAM host", "Lite install + small model", "text chat works")], "DEMO-PERF-004", None, None),
        ("REQ-PERF-005", "BVT runtime budget documented",
         "Behavioral verification tests shall declare an expected runtime budget when published.",
         "Performance", "P2", "CI / operator reproduce.", "BVT tests", None, [], "Inspection", "Design Intent",
         [gwt("BVT procedure", "reviewed", "budget stated or Not yet published")], None, None, None),
        ("REQ-PERF-006", "Benchmark N published",
         "MEASURED benchmark rows shall publish N (run count).",
         "Performance", "P1", "Statistics honesty.", "Benchmarks", None, [], "Inspection", "Implemented",
         [gwt("MEASURED row", "N field", "present")], "INSP-PERF-006", None, None),
        ("REQ-PERF-007", "Codec round-trip class",
         "Benchmark plan shall include Codec round-trip latency as a class.",
         "Performance", "P2", "BENCH-PLAN-001.", "Benchmarks plan", None, [], "Inspection", "Implemented",
         [gwt("plan", "classes", "Codec round-trip listed")], "INSP-PERF-007", None, None),
        ("REQ-IF-001", "HTTP JSON API contract",
         "Core shall expose a documented HTTP JSON API for UI/agent requests (IF-002 class).",
         "Interface", "P0", "IBD typed flows.", "interfaces.json / IBD-001", "REQ-CODEC-001", ["ARCH-007"], "Test", "Verification Pending",
         [gwt("API docs", "sample request", "documented schema")], None, ["IT-002"], None),
        ("REQ-IF-002", "Ollama inference interface",
         "Model runtime integration shall use a documented inference request interface (IF-001 class).",
         "Interface", "P0", "SysML IBD.", "IF-001", "REQ-ROUTE-003", ["ARCH-004", "ARCH-005"], "Test", "Verification Pending",
         [gwt("Ollama up", "inference request", "completion returned")], None, ["IT-001"], None),
        ("REQ-IF-003", "OS feature ops interface",
         "Installer OS feature operations shall be isolated behind a documented IF-003-style boundary.",
         "Interface", "P1", "IBD installer→OS.", "IF-003 / RSK-005", "REQ-INST-002", ["ARCH-011"], "Inspection", "Design Intent",
         [gwt("architecture docs", "IF-003", "described")], "INSP-IF-003", None, ["RSK-005"]),
        ("REQ-IF-004", "Discord optional adapter",
         "Discord integration shall be optional and disabled unless configured.",
         "Interface", "P1", "Externals optional tier.", "EXT-DISCORD", "REQ-SYS-001", ["ARCH-009"], "Test", "Verification Pending",
         [gwt("fresh install", "no Discord config", "no Discord traffic")], None, None, None),
        ("REQ-IF-005", "Home Assistant optional adapter",
         "Home Assistant integration shall be optional and disabled unless configured.",
         "Interface", "P1", "Externals optional.", "EXT-HA", "REQ-SYS-001", ["ARCH-009"], "Test", "Verification Pending",
         [gwt("fresh install", "no HA config", "no HA calls")], None, None, None),
        ("REQ-IF-006", "API schema examples",
         "API documentation shall include schema examples or OpenAPI when available.",
         "Interface", "P2", "Integrators need examples.", "IF-002", "REQ-IF-001", ["ARCH-007"], "Inspection", "Design Intent",
         [gwt("API docs", "examples", "present or Not yet published")], None, None, None),
        ("REQ-IF-007", "Websocket optional",
         "Realtime channels, if any, shall be optional and documented separately from HTTP JSON.",
         "Interface", "P2", "Keep HTTP as baseline.", "Interfaces", "REQ-IF-001", ["ARCH-007"], "Inspection", "Design Intent",
         [gwt("docs", "realtime", "optional")], None, None, None),
        ("REQ-REL-001", "Service restart recovers Core",
         "After unexpected process stop, restarting the Core service shall restore API/Codec reachability without reinstall.",
         "Reliability", "P0", "Ops baseline.", "Deployment", "REQ-SYS-001", ["ARCH-001"], "Test", "Verification Pending",
         [gwt("service killed", "restart", "health OK")], None, None, None),
        ("REQ-REL-002", "Installer failure classifies",
         "Installer failures shall classify stage and point to log path.",
         "Reliability", "P1", "ACT-002 recovery.", "ACT-002", "REQ-INST-003", ["ARCH-011"], "Test", "Verification Pending",
         [gwt("forced failure", "exit", "stage + log path shown")], None, None, ["RSK-005"]),
        ("REQ-REL-003", "Log rotation design intent",
         "Service logs shall have a documented rotation or size-management approach.",
         "Reliability", "P2", "Disk fill risk.", "Ops", None, ["ARCH-001"], "Inspection", "Design Intent",
         [gwt("docs", "log rotation", "present or Design Intent")], None, None, None),
        ("REQ-REL-004", "Health endpoint",
         "Core shall expose a health/ready check for local monitoring.",
         "Reliability", "P1", "Installer health gate + ops.", "REQ-INST-008", "REQ-INST-008", ["ARCH-001"], "Test", "Verification Pending",
         [gwt("service up", "health check", "success")], None, None, None),
        ("REQ-AVAIL-001", "Local offline chat path",
         "With local model runtime available, Codec text chat shall not require WAN connectivity.",
         "Availability", "P0", "Local-first.", "REQ-SYS-001", "REQ-SYS-001", ["ARCH-004", "ARCH-005"], "Test", "Verification Pending",
         [gwt("WAN blocked; Ollama up", "message", "reply returns")], None, None, None),
        ("REQ-ENG-001", "Public requirements register",
         "Engineering portal shall publish a structured requirements register with unique IDs.",
         "Maintainability", "P0", "Digital engineering evidence.", "Engineering portal", None, [], "Inspection", "Implemented",
         [gwt("Engineering Requirements", "open", "≥100 REQ IDs listed")], "INSP-ENG-001", None, None),
        ("REQ-ENG-002", "VCRM Planned vs Executed",
         "VCRM shall distinguish Planned vs Executed verification columns.",
         "Maintainability", "P0", "Pending ≠ PASS.", "VCRM", None, [], "Inspection", "Implemented",
         [gwt("VCRM open", "columns", "Planned and Executed present")], "INSP-ENG-002", None, None),
        ("REQ-ENG-003", "No fabricated PASS",
         "Engineering JSON shall not mark Verified/PASS without evidence objects.",
         "Maintainability", "P0", "Accuracy policy.", "meta accuracy_policy", None, [], "Test", "Implemented",
         [gwt("validator + audit", "scan", "no orphan PASS")], "PROC-ENG-003", ["SEC-001"], None),
        ("REQ-ENG-004", "Continuity Model published",
         "Engineering Math shall publish Continuity Model equations CM-01…CM-25 with write-ups.",
         "Maintainability", "P0", "User Continuity Model manual.", "Math tab", None, [], "Inspection", "Implemented",
         [gwt("Math tab", "TOC", "CM-01 through CM-25")], "INSP-ENG-004", None, None),
        ("REQ-ENG-005", "Risk narratives",
         "Published risks shall include scenario, cause chain, and mitigation strategy depth.",
         "Maintainability", "P1", "Audit P0 risk cards.", "Risk tab", None, [], "Inspection", "Implemented",
         [gwt("Risk cards", "RSK-005", "roadmap/narrative present")], "INSP-ENG-005", None, None),
        ("REQ-ENG-006", "Analysis MOCK watermark",
         "Analysis datasets that are synthetic shall be labeled MOCK/SYNTHETIC.",
         "Maintainability", "P0", "Honesty.", "Analysis tab", None, [], "Inspection", "Implemented",
         [gwt("Analysis", "datasets", "MOCK labels")], "INSP-ENG-006", None, None),
        ("REQ-ENG-007", "Traceability links",
         "Requirements shall support links to architecture and tests where allocated.",
         "Maintainability", "P1", "RTM/VCRM.", "Traceability", None, [], "Inspection", "Implemented",
         [gwt("requirement drawer", "links", "arch/tests fields exist")], "INSP-ENG-007", None, None),
        ("REQ-ENG-008", "Schema version published",
         "Engineering meta shall publish schema_version and last_audited date.",
         "Maintainability", "P1", "Configuration baseline.", "meta.json", None, [], "Inspection", "Implemented",
         [gwt("meta.json", "fields", "schema_version + last_audited")], "INSP-ENG-008", None, None),
        ("REQ-ENG-009", "Requirements baseline ID",
         "Requirements package shall publish baseline_id.",
         "Maintainability", "P1", "Configuration management.", "requirements.json", None, [], "Inspection", "Implemented",
         [gwt("requirements.json", "baseline_id", "present")], "INSP-ENG-009", None, None),
        ("REQ-ENG-010", "Known issues register",
         "Engineering shall publish a Known Issues register.",
         "Maintainability", "P1", "Honesty debt tracker.", "Issues tab", None, [], "Inspection", "Implemented",
         [gwt("Issues tab", "open", "register present")], "INSP-ENG-010", None, None),
        ("REQ-ENG-011", "Releases register",
         "Engineering shall publish a Releases/qualification register.",
         "Maintainability", "P1", "Configuration baseline.", "Releases tab", None, [], "Inspection", "Implemented",
         [gwt("Releases tab", "open", "register present")], "INSP-ENG-011", None, None),
        ("REQ-TOOL-001", "Tool calls optional",
         "Agent tool execution shall be optional per request/capability and fail safely when tools are disabled.",
         "Functional", "P1", "Architecture ToolLayer.", "ARCH tools", "REQ-FUNC-001", ["ARCH-006"], "Test", "Verification Pending",
         [gwt("tools disabled", "chat", "reply without tool side effects")], None, None, None),
        ("REQ-TOOL-002", "REX not Lite-default claim",
         "Public Lite claims shall not list REX propose→verify as a Lite-default surface.",
         "Operational", "P0", "Overview capability matrix red for Lite REX.", "Overview matrix", None, [], "Inspection", "Implemented",
         [gwt("Overview matrix", "REX row Lite", "NO/red")], "INSP-TOOL-002", None, None),
        ("REQ-TOOL-003", "REX states documented",
         "When REX is in scope for a deployment, proposal states shall follow the documented STM-001 lifecycle.",
         "Functional", "P2", "STM-001.", "Reference Keep / executor", None, ["ARCH-006"], "Inspection", "Design Intent",
         [gwt("STM-001", "reviewed", "states listed")], "INSP-TOOL-003", None, None),
        ("REQ-OPS-001", "Discord support channel published",
         "A public Discord invite for support shall remain linked from site chrome.",
         "Operational", "P1", "Human support path.", "FAQ", None, [], "Inspection", "Implemented",
         [gwt("site nav", "Discord", "present")], "INSP-OPS-001", None, None),
        ("REQ-OPS-002", "FAQ install triage",
         "FAQ shall include install triage for Lite and Expansion foundation failures.",
         "Usability", "P1", "Support deflection.", "FAQ", None, [], "Inspection", "Implemented",
         [gwt("FAQ", "Expansion READY", "documented")], "INSP-OPS-002", None, None),
        ("REQ-OPS-003", "Engineering FAQ honesty",
         "FAQ shall explain Verified, Pending VCRM, and Lite vs Reference claims.",
         "Usability", "P1", "Audit FAQ eng section.", "FAQ engineering", None, [], "Inspection", "Implemented",
         [gwt("FAQ#engineering-faq", "open", "Verified meaning present")], "INSP-OPS-003", None, None),
        ("REQ-OPS-004", "About deep-links to Math",
         "About measurable-emotion section shall deep-link to Engineering Math/Behavioral Models.",
         "Usability", "P2", "Site cohesion.", "About", None, [], "Inspection", "Implemented",
         [gwt("About#measurable", "links", "Math/BVT")], "INSP-OPS-004", None, None),
        ("REQ-OPS-005", "Home proof strip",
         "Home page shall show a live-ish evidence proof strip sourced from Engineering counts.",
         "Usability", "P2", "Audit Home proof strip.", "Home", None, [], "Inspection", "Implemented",
         [gwt("Home", "proof strip", "reqs/verified/risks chips")], "INSP-OPS-005", None, None),
        ("REQ-OPS-006", "Status page honesty",
         "Expansion status page shall distinguish shipped vs roadmap items.",
         "Operational", "P1", "Avoid vapor claims.", "Expansion", None, [], "Inspection", "Implemented",
         [gwt("Expansion page", "shipped vs roadmap", "distinguishable")], "INSP-OPS-006", None, None),
        ("REQ-OPS-007", "Attribution page",
         "About shall include inspiration/attribution disclaimers for Metal Gear references.",
         "Operational", "P1", "Legal/brand hygiene.", "About attribution", None, [], "Inspection", "Implemented",
         [gwt("About#attribution", "disclaimer", "present")], "INSP-OPS-007", None, None),
        ("REQ-AI-002", "No OK-trained foundation claim",
         "Public Models & Data shall state OtaconsKeep does not claim to have trained the third-party foundation weights it routes to.",
         "AI/Model", "P0", "Provenance honesty.", "models.json", None, [], "Inspection", "Implemented",
         [gwt("Models tab", "fine_tuned flag", "false for foundations")], "INSP-AI-002", None, None),
        ("REQ-AI-003", "Quantization documented in benches",
         "MEASURED benchmark rows shall state model family and quantization when applicable.",
         "AI/Model", "P1", "Reproducibility.", "Benchmarks", None, [], "Inspection", "Implemented",
         [gwt("MEASURED GPU row", "fields", "model + quant present")], "INSP-AI-003", None, None),
        ("REQ-AI-004", "Personality not prompt-only goal",
         "Continuity-enabled agents shall treat personality parameters as numeric modulators, not solely a system-prompt adjective list.",
         "AI/Model", "P1", "About personality thesis.", "MOD-PER-001", "REQ-BEH-007", ["ARCH-002"], "Test", "Verification Pending",
         [gwt("profiles differ", "same event", "numeric Δ differs")], None, ["BVT-002"], None),
        ("REQ-AI-005", "Context window honesty",
         "Docs shall not imply infinite context; long chats may summarize or truncate per implementation.",
         "AI/Model", "P2", "Expectation management.", "Docs", None, ["ARCH-004"], "Inspection", "Design Intent",
         [gwt("docs", "context", "limits acknowledged")], None, None, None),
        ("REQ-AI-006", "Temperature defaults documented",
         "Default sampling parameters shall be documented or visible in config.",
         "AI/Model", "P2", "Reproducibility.", "Config", "REQ-ROUTE-001", ["ARCH-004"], "Inspection", "Design Intent",
         [gwt("config/docs", "temperature", "visible")], None, None, None),
        ("REQ-NET-002", "Optional WAN features degrade",
         "Optional WAN features (providers, Discord) shall degrade without breaking local Core chat.",
         "Network", "P1", "Availability.", "REQ-AVAIL-001", "REQ-AVAIL-001", ["ARCH-009"], "Test", "Verification Pending",
         [gwt("WAN down", "local chat", "works")], None, None, None),
        ("REQ-NET-003", "Proxy documentation design intent",
         "Corporate proxy/TLS interception notes shall be documented as Design Intent for Windows install.",
         "Network", "P2", "Enterprise installs.", "Install support", "REQ-INST-001", ["ARCH-011"], "Inspection", "Design Intent",
         [gwt("docs", "proxy", "noted or Not yet published")], None, None, None),
        ("REQ-NET-004", "Rate limit design intent",
         "Design Intent: local API should eventually support simple rate limiting for non-loopback binds.",
         "Network", "P2", "If operators expose beyond loopback.", "Security", "REQ-SEC-005", ["ARCH-007"], "Inspection", "Design Intent",
         [gwt("docs", "rate limit", "Design Intent noted")], None, None, None),
        ("REQ-SW-002", "Unit tests for clamp/blend",
         "Clamp and blend helpers shall have unit tests in the continuity test inventory.",
         "Software", "P1", "UT-001/002.", "tests.json", "REQ-BEH-003", ["ARCH-002"], "Test", "Verification Pending",
         [gwt("UT-001/002", "register", "linked to continuity")], None, ["UT-001", "UT-002"], None),
        ("REQ-SW-003", "Public validator script",
         "Repository shall include validate-engineering.py (or successor) enforcing ID uniqueness and secret scan.",
         "Software", "P0", "CI-ish honesty gate.", "scripts/", None, [], "Test", "Implemented",
         [gwt("script run", "on data", "exit 0")], "PROC-SW-003", None, None),
        ("REQ-SW-004", "Status vocabulary enforced",
         "Requirement and risk statuses shall use the published status vocabulary.",
         "Software", "P1", "meta status_vocabulary.", "meta.json", None, [], "Test", "Implemented",
         [gwt("validator", "statuses", "accepted set")], "PROC-SW-004", None, None),
        ("REQ-SW-005", "Public site static hosting",
         "Public engineering site shall be statically hostable (no server secrets required to render).",
         "Software", "P0", "GitHub Pages deployment.", "Pages", None, [], "Inspection", "Implemented",
         [gwt("site", "static JSON fetch", "renders")], "INSP-SW-005", None, None),
        ("REQ-SW-006", "Mermaid diagrams client-side",
         "SysML diagrams shall render via client-side Mermaid without private network calls beyond CDN.",
         "Software", "P2", "Public diagrams.", "System Models", None, [], "Inspection", "Implemented",
         [gwt("diagrams", "Mermaid", "client render")], "INSP-SW-006", None, None),
        ("REQ-DATA-001", "Operator data locality",
         "Default Lite path shall keep conversation/memory on operator-controlled storage.",
         "Data", "P0", "Mission local-first.", "REQ-SYS-001", "REQ-SYS-001", ["ARCH-003"], "Demonstration", "Implemented",
         [gwt("install", "data path", "under operator machine")], "DEMO-DATA-001", None, None),
        ("REQ-DATA-002", "No training on operator chats by default",
         "Lite shall not upload operator chats for OtaconsKeep model training by default.",
         "Data", "P0", "Trust.", "Privacy posture", "REQ-SYS-001", ["ARCH-001"], "Inspection", "Implemented",
         [gwt("docs/defaults", "reviewed", "no default upload-for-training")], "INSP-DATA-002", None, None),
        ("REQ-DATA-003", "Export/delete design intent",
         "Design Intent: operators in regulated contexts should eventually export/delete local agent data via documented tools.",
         "Data", "P2", "Future compliance tooling.", "Privacy", "REQ-MEM-004", ["ARCH-003"], "Inspection", "Design Intent",
         [gwt("docs", "export/delete", "Design Intent noted")], None, None, None),
        ("REQ-DATA-004", "No identifying telemetry by default",
         "Lite shall not enable identifying telemetry by default.",
         "Data", "P0", "Local-first privacy.", "Privacy", "REQ-SYS-001", ["ARCH-001"], "Inspection", "Implemented",
         [gwt("defaults", "telemetry", "off")], "INSP-DATA-004", None, None),
        ("REQ-HW-002", "GPU optional",
         "A discrete NVIDIA GPU shall be optional for basic text Lite operation.",
         "Hardware", "P0", "CPU fallback.", "REQ-PERF-004", "REQ-HW-001", ["ARCH-005"], "Demonstration", "Verification Pending",
         [gwt("no GPU", "small model", "chat works")], "DEMO-HW-002", None, None),
        ("REQ-HW-003", "VRAM table published",
         "Public materials shall publish VRAM tier guidance for Default Model selection.",
         "Hardware", "P1", "Hardware page / benches.", "Hardware", "REQ-ROUTE-002", ["ARCH-005"], "Inspection", "Implemented",
         [gwt("VRAM tiers", "published", "visible")], "INSP-HW-003", None, None),
        ("REQ-HW-004", "Measured SKU honesty",
         "Only GPUs actually measured may be labeled MEASURED in Engineering benchmarks.",
         "Hardware", "P0", "MEASURED = 2060/3090/5070 Ti rule.", "Benchmarks disclaimer", None, [], "Inspection", "Implemented",
         [gwt("benchmarks", "MEASURED set", "subset of available SKUs")], "INSP-HW-004", None, None),
        ("REQ-HW-005", "Multi-GPU non-requirement",
         "Lite shall not require multi-GPU for basic operation.",
         "Hardware", "P1", "Keep hardware floor honest.", "Hardware", "REQ-HW-002", ["ARCH-005"], "Inspection", "Implemented",
         [gwt("docs", "multi-GPU", "not required")], "INSP-HW-005", None, None),
        ("REQ-FUNC-003", "Multi-agent roster Expansion",
         "Expansion shall support a multi-agent roster beyond a single default agent.",
         "Functional", "P0", "Expansion product.", "Expansion", "REQ-EXP-002", ["ARCH-002"], "Demonstration", "Implemented",
         [gwt("Expansion installed", "roster", "multiple agents listed")], "DEMO-FUNC-003", None, None),
        ("REQ-FUNC-004", "Agent identity fields",
         "Agents shall have durable identity fields (name/id) independent of the underlying model ID.",
         "Functional", "P0", "Identity vs model.", "Architecture AgentRuntime", "REQ-FUNC-001", ["ARCH-002"], "Test", "Verification Pending",
         [gwt("agent created", "model changed", "agent id unchanged")], None, None, None),
        ("REQ-FUNC-005", "Genome voice trainer path",
         "Lite docs shall include Genome Voice Trainer as an included path where applicable.",
         "Functional", "P1", "Overview in-scope.", "Overview", "REQ-CODEC-005", ["ARCH-008"], "Inspection", "Implemented",
         [gwt("docs", "Genome", "mentioned")], "INSP-FUNC-005", None, None),
        ("REQ-FUNC-006", "Command Center navigation",
         "Command Center shall provide navigation among primary Keep surfaces without external browser search.",
         "Usability", "P1", "Deck UX.", "Keep Desk / Expansion", "REQ-CODEC-001", ["ARCH-007"], "Demonstration", "Verification Pending",
         [gwt("Command Center open", "navigate", "Codec reachable")], "DEMO-FUNC-006", None, None),
        ("REQ-FUNC-007", "Agent delete confirmation",
         "Deleting an agent shall require confirmation when UI supports delete.",
         "Usability", "P2", "Prevent accidental wipe.", "UX", "REQ-FUNC-001", ["ARCH-002", "ARCH-007"], "Test", "Design Intent",
         [gwt("delete clicked", "confirm", "required")], None, None, None),
        ("REQ-FUNC-008", "Default agent present",
         "Fresh Lite install shall provide at least one usable default agent path.",
         "Functional", "P0", "Out-of-box chat.", "Lite", "REQ-FUNC-001", ["ARCH-002"], "Demonstration", "Verification Pending",
         [gwt("fresh install", "Codec", "default agent usable")], "DEMO-FUNC-008", None, None),
        ("REQ-FUNC-009", "Tools permission gate",
         "Destructive tools shall require explicit enablement or confirmation where implemented.",
         "Security", "P1", "Tool safety.", "ToolLayer", "REQ-TOOL-001", ["ARCH-006"], "Test", "Design Intent",
         [gwt("destructive tool", "invoke", "gate/confirm")], None, None, None),
        ("REQ-FUNC-010", "Session concurrency note",
         "Docs shall note single-operator local concurrency expectations for Lite.",
         "Reliability", "P2", "Expectation management.", "Docs", "REQ-SYS-001", ["ARCH-001"], "Inspection", "Design Intent",
         [gwt("docs", "concurrency", "noted")], None, None, None),
        ("REQ-MAINT-001", "Changelog pointer",
         "Releases shall point to changelog or commit identity when qualified.",
         "Maintainability", "P2", "Traceability to builds.", "Releases", None, [], "Inspection", "Design Intent",
         [gwt("release record", "pointer", "present or Not yet published")], None, None, None),
        ("REQ-MAINT-002", "Diagram fullscreen",
         "System Models shall support fullscreen viewing of diagrams.",
         "Maintainability", "P2", "Readable SysML.", "System Models", None, [], "Inspection", "Implemented",
         [gwt("diagram", "fullscreen control", "present")], "INSP-MAINT-002", None, None),
        ("REQ-USAB-001", "Keyboard focus basics",
         "Primary Codec input shall be keyboard-focusable.",
         "Usability", "P1", "Accessibility baseline.", "Codec", "REQ-CODEC-001", ["ARCH-007"], "Test", "Design Intent",
         [gwt("Codec open", "Tab/focus", "input focusable")], None, None, None),
        ("REQ-USAB-002", "Contrast readable",
         "Engineering portal text shall remain readable on the dark VOID theme.",
         "Usability", "P1", "Portal usability.", "Engineering CSS", None, [], "Inspection", "Implemented",
         [gwt("Engineering pages", "text", "readable")], "INSP-USAB-002", None, None),
        ("REQ-USAB-003", "Mobile nav works",
         "Site topnav shall function on narrow viewports.",
         "Usability", "P1", "Mobile operators.", "site.js", None, [], "Inspection", "Implemented",
         [gwt("narrow viewport", "MENU", "opens links")], "INSP-USAB-003", None, None),
    ]

    for row in extras:
        (rid, title, text, cat, pri, rat, src, parent, arch, method, status, acc, planned, tids, rids) = row
        add(R(rid, title, text, cat, pri, rat, src, parent, arch, method, status, acc,
              planned, tids, rids, model_ids=model_ids))

    # Pad to >= 102 with systematic REQ-GEN if somehow short
    n = 1
    while len(existing) < 102:
        rid = f"REQ-GEN-{n:03d}"
        n += 1
        if rid in existing:
            continue
        add(R(
            rid,
            f"General allocation requirement {n-1:03d}",
            f"The system shall document and track general public obligation {n-1:03d} in the Engineering register until allocated to a specific subsystem.",
            "Maintainability", "P2",
            "Baseline completeness: public register minimum 102 requirements.",
            "BL-REQ-0003", None, ["ARCH-001"], "Inspection", "Design Intent",
            [gwt("register open", f"{rid} present", "acceptance reviewable")],
            model_ids=model_ids,
        ))

    ordered = sorted(existing.values(), key=lambda r: r["id"])
    data["requirements"] = ordered
    data["baseline_id"] = "BL-REQ-0003"
    data["baseline_status"] = "Draft"
    data["notes"] = (
        f"Public requirements baseline BL-REQ-0003 with {len(ordered)} shall-statements "
        "(rationale, G/W/T acceptance, planned vs executed). "
        "No requirement is Verified solely because code exists. Minimum target: 102."
    )
    REQ_PATH.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"Wrote {len(ordered)} requirements to {REQ_PATH}")


if __name__ == "__main__":
    main()
